/** 内蔵 Live デバイス名の参考カタログ（insert_device / do CREATE Device 用）。 */
export const BUILT_IN_DEVICE_CATALOG = {
    instruments: [
        "Operator",
        "Wavetable",
        "Analog",
        "Collision",
        "Electric",
        "Tension",
        "Drift",
        "Meld",
        "Sampler",
        "Simpler",
        "Drum Rack",
        "Impulse",
        "Poli",
    ],
    audioEffects: [
        "Reverb",
        "Hybrid Reverb",
        "Delay",
        "Echo",
        "EQ Eight",
        "EQ Three",
        "Compressor",
        "Glue Compressor",
        "Limiter",
        "Gate",
        "Auto Filter",
        "Saturator",
        "Overdrive",
        "Utility",
        "Auto Pan",
        "Chorus-Ensemble",
        "Phaser-Flanger",
        "Redux",
        "Drum Buss",
        "Pedal",
        "Amp",
        "Cabinet",
        "Corpus",
        "Resonators",
    ],
    midiEffects: ["Arpeggiator", "Chord", "Scale", "Note Length", "Pitch", "Random", "Velocity"],
} as const

export const CATALOG_DEVICE_NAMES: string[] = [
    ...BUILT_IN_DEVICE_CATALOG.instruments,
    ...BUILT_IN_DEVICE_CATALOG.audioEffects,
    ...BUILT_IN_DEVICE_CATALOG.midiEffects,
]
